/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eleicao.cadastro;

import eleicao.ContainerCandidatos;
import eleicao.TelaPrincipal;

/**
 *
 * @author Caio Lucas Batista Nascimento
 * @matricula 184450029
 */
public class telaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cdstPresidente = new javax.swing.JButton();
        cdstGovernador = new javax.swing.JButton();
        cdstSenador = new javax.swing.JButton();
        cdstDepFed = new javax.swing.JButton();
        cdstDepEst = new javax.swing.JButton();
        voltarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cadastrar: ");

        cdstPresidente.setText("Presidente");
        cdstPresidente.setName(""); // NOI18N
        cdstPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdstPresidenteActionPerformed(evt);
            }
        });

        cdstGovernador.setText("Governador");
        cdstGovernador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdstGovernadorActionPerformed(evt);
            }
        });

        cdstSenador.setText("Senador");
        cdstSenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdstSenadorActionPerformed(evt);
            }
        });

        cdstDepFed.setText("Deputado Federal");
        cdstDepFed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdstDepFedActionPerformed(evt);
            }
        });

        cdstDepEst.setText("Deputado Estadual");
        cdstDepEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdstDepEstActionPerformed(evt);
            }
        });

        voltarbutton.setText("Voltar");
        voltarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdstDepFed, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdstSenador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdstGovernador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addComponent(cdstPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdstDepEst, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voltarbutton)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdstPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdstGovernador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdstSenador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdstDepFed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cdstDepEst, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarbutton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdstPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdstPresidenteActionPerformed
        new cadastroPresidente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cdstPresidenteActionPerformed

    private void cdstGovernadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdstGovernadorActionPerformed
        new cadastroGovernador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cdstGovernadorActionPerformed

    private void cdstSenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdstSenadorActionPerformed
        new cadastroSenador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cdstSenadorActionPerformed

    private void cdstDepFedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdstDepFedActionPerformed
        new cadastroDepFed().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cdstDepFedActionPerformed

    private void cdstDepEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdstDepEstActionPerformed
        new cadastroDepEst().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cdstDepEstActionPerformed

    private void voltarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarbuttonActionPerformed
        this.setVisible(false);
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_voltarbuttonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdstDepEst;
    private javax.swing.JButton cdstDepFed;
    private javax.swing.JButton cdstGovernador;
    private javax.swing.JButton cdstPresidente;
    private javax.swing.JButton cdstSenador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voltarbutton;
    // End of variables declaration//GEN-END:variables
}
